apiVersion : apps/v1
kind: Deployment
metadata:
  name: "dnazurekubernate-b350"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "dnazurekubernate-b350"
  template:
    metadata:
      labels:
        app: "dnazurekubernate-b350"
    spec:
      containers:
        - name: "dnazurekubernate-b350"
          image: "orderitemregistry.azurecr.io/dnazurekubernate"
          ports:
          - containerPort: 80