apiVersion: v1
kind: Service
metadata:
    name: "dnazurekubernate-b350"
    labels:
        app: "dnazurekubernate-b350"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "dnazurekubernate-b350"